# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.2.0
#     hooks:
#     -   id: trailing-whitespace
#     -   id: end-of-file-fixer
#     -   id: check-yaml
#     -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|scss)$
        exclude: README.md

-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.13

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args: [--fix, --ignore=B008]
